name: Build TDLib on Windows

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build-tdlib:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Read specific commit hash from file (PowerShell)
      id: get-commit
      shell: powershell
      run: |
        $COMMIT_HASH = Get-Content tdlib-commit.txt -Raw | Select-Object -First 1
        $COMMIT_HASH = $COMMIT_HASH.Trim()
        echo "COMMIT_HASH=$COMMIT_HASH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "Read commit hash: $COMMIT_HASH"

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        architecture: x64
        
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64
        
    - name: Install CMake (3.10+)
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: 3.27.0  # 指定明确的3.10+版本，避免默认版本问题
      
    - name: Clone TDLib repository
      shell: powershell
      run: |
        git clone https://github.com/tdlib/td.git
        cd td
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        git checkout bc3512a509f9d29b37346a7e7e929f9a26e66c7e  # 稳定版本
      
    - name: Bootstrap vcpkg
      shell: powershell
      run: |
        cd td/vcpkg
        ./bootstrap-vcpkg.bat
        echo "${{ github.workspace }}\td\vcpkg" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      
    - name: Install dependencies with vcpkg
      shell: powershell
      run: |
        vcpkg install gperf:x64-windows openssl:x64-windows zlib:x64-windows
        vcpkg integrate install
      
    - name: Checkout specific TDLib commit
      shell: powershell
      run: |
        cd td
        git checkout $env:COMMIT_HASH
        echo "Checked out commit: $env:COMMIT_HASH"
        
    - name: Build and install TDLib
      shell: powershell
      run: |
        cd td
        if (Test-Path "build") { Remove-Item "build" -Recurse -Force }
        New-Item -ItemType Directory -Path "build" | Out-Null
        cd build
        # 修复：使用符合格式的3.10版本（TDLib要求的最低版本）
        cmake -G "Visual Studio 17 2022" -A x64 `
          -DCMAKE_MINIMUM_REQUIRED_VERSION=3.10 `
          -DCMAKE_POLICY_VERSION_MINIMUM=3.10 `
          -DCMAKE_INSTALL_PREFIX:PATH=../example/java/td `
          -DTD_ENABLE_JNI=ON `
          -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../vcpkg/scripts/buildsystems/vcpkg.cmake `
          ..
        cmake --build . --target install --config Release
      
    - name: Build and install Java example
      shell: powershell
      run: |
        cd td/example/java
        if (Test-Path "build") { Remove-Item "build" -Recurse -Force }
        New-Item -ItemType Directory -Path "build" | Out-Null
        cd build
        $tdDir = Resolve-Path ../td/lib/cmake/Td | Select-Object -ExpandProperty Path
        # 同样修复版本参数格式
        cmake -G "Visual Studio 17 2022" -A x64 `
          -DCMAKE_MINIMUM_REQUIRED_VERSION=3.10 `
          -DCMAKE_POLICY_VERSION_MINIMUM=3.10 `
          -DCMAKE_INSTALL_PREFIX:PATH=../../../tdlib `
          -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../../../vcpkg/scripts/buildsystems/vcpkg.cmake `
          -DTd_DIR:PATH="$tdDir" `
          ..
        cmake --build . --target install --config Release
      
    - name: Package and upload artifacts
      shell: powershell
      run: |
        cd td
        if (Test-Path "tdlib") {
          dir tdlib -Recurse
        } else {
          echo "tdlib directory not found!"
        }
      
    - name: Package Java classes into JAR
      shell: powershell
      run: |
        cd td/tdlib/bin
        # 检查class文件是否存在
        if (Test-Path "org/drinkless/tdlib/example/Example.class") {
          jar cvfe tdlib.jar org.drinkless.tdlib.example.Example .
          mv tdlib.jar ../
        } else {
          echo "Warning: Example.class not found, skipping JAR packaging"
        }
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tdlib-windows-build
        path: |
          td/tdlib/
          td/tdlib/tdlib.jar
        retention-days: 30
    