name: Build TDLib on Windows

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build-tdlib:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Read specific commit hash from file (PowerShell)
      id: get-commit
      shell: powershell
      run: |
        # 在PowerShell中正确读取文件内容（去除换行和空格）
        $COMMIT_HASH = Get-Content tdlib-commit.txt -Raw | Select-Object -First 1
        $COMMIT_HASH = $COMMIT_HASH.Trim()  # 移除可能的空格和换行符
        echo "COMMIT_HASH=$COMMIT_HASH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "Read commit hash: $COMMIT_HASH"

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        architecture: x64
        
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64
        
    - name: Install CMake
      uses: lukka/get-cmake@latest
      
    - name: Clone TDLib repository
      shell: powershell
      run: |
        git clone https://github.com/tdlib/td.git
        cd td
        # 克隆vcpkg并使用已知稳定版本
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        git checkout bc3512a509f9d29b37346a7e7e929f9a26e66c7e
      
    - name: Bootstrap vcpkg
      shell: powershell
      run: |
        cd td/vcpkg
        ./bootstrap-vcpkg.bat
        # 确保vcpkg可执行文件在PATH中
        echo "${{ github.workspace }}\td\vcpkg" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      
    - name: Install dependencies with vcpkg
      shell: powershell
      run: |
        vcpkg install gperf:x64-windows openssl:x64-windows zlib:x64-windows
        vcpkg integrate install  # 全局集成vcpkg工具链
        
    - name: Checkout specific TDLib commit
      shell: powershell
      run: |
        cd td
        git checkout $env:COMMIT_HASH
        echo "Checked out commit: $env:COMMIT_HASH"
        
    - name: Build and install TDLib
      shell: powershell
      run: |
        cd td
        # 清理旧构建目录（PowerShell语法）
        if (Test-Path "build") {
          Remove-Item "build" -Recurse -Force
        }
        New-Item -ItemType Directory -Path "build" | Out-Null
        cd build
        # Windows特定CMake配置：添加版本兼容性参数
        cmake -G "Visual Studio 17 2022" -A x64 `
          -DCMAKE_MINIMUM_REQUIRED_VERSION=3.5 `
          -DCMAKE_POLICY_VERSION_MINIMUM=3.5 `
          -DCMAKE_INSTALL_PREFIX:PATH=../example/java/td `
          -DTD_ENABLE_JNI=ON `
          -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../vcpkg/scripts/buildsystems/vcpkg.cmake `
          ..
        # 构建并安装（Release配置）
        cmake --build . --target install --config Release
      
    - name: Build and install Java example
      shell: powershell
      run: |
        cd td/example/java
        if (Test-Path "build") {
          Remove-Item "build" -Recurse -Force
        }
        New-Item -ItemType Directory -Path "build" | Out-Null
        cd build
        # 正确解析Td_DIR路径（PowerShell的Resolve-Path处理）
        $tdDir = Resolve-Path ../td/lib/cmake/Td | Select-Object -ExpandProperty Path
        cmake -G "Visual Studio 17 2022" -A x64 `
          -DCMAKE_MINIMUM_REQUIRED_VERSION=3.5 `
          -DCMAKE_POLICY_VERSION_MINIMUM=3.5 `
          -DCMAKE_INSTALL_PREFIX:PATH=../../../tdlib `
          -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../../../vcpkg/scripts/buildsystems/vcpkg.cmake `
          -DTd_DIR:PATH="$tdDir" `
          ..
        cmake --build . --target install --config Release
      
    - name: List output directory (debug)
      shell: powershell
      run: |
        cd td
        if (Test-Path "tdlib") {
          dir tdlib -Recurse
        } else {
          echo "tdlib directory not found!"
        }
      
    - name: Package Java classes into JAR
      shell: powershell
      run: |
        cd td/tdlib/bin
        # 检查class文件是否存在
        if (Test-Path "org/drinkless/tdlib/example/Example.class") {
          jar cvfe tdlib.jar org.drinkless.tdlib.example.Example .
          mv tdlib.jar ../
        } else {
          echo "Warning: Example.class not found, skipping JAR packaging"
        }
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tdlib-windows-build
        path: |
          td/tdlib/
          td/tdlib/tdlib.jar
        retention-days: 30
    