name: Build TDLib on Ubuntu 22.04

on:
  workflow_dispatch:

jobs:
  build-tdlib:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Update and upgrade system packages
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y
        
    - name: Install required dependencies
      run: |
        sudo apt-get install -y make git zlib1g-dev libssl-dev gperf php-cli cmake default-jdk g++
        
    - name: Clone TDLib repository
      run: |
        git clone https://github.com/tdlib/td.git
        
    - name: Build and install TDLib
      run: |
        cd td
        rm -rf build
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../example/java/td -DTD_ENABLE_JNI=ON ..
        cmake --build . --target install
        cd ..
        cd example/java
        rm -rf build
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../../../tdlib -DTd_DIR:PATH=$(readlink -e ../td/lib/cmake/Td) ..
        cmake --build . --target install
        cd ../../..
        cd ..
        
    - name: List build results
      run: |
        ls -l td/tdlib
        
    - name: Upload TDLib artifacts
      uses: actions/upload-artifact@v3
      with:
        name: tdlib-binaries
        path: td/tdlib/
