name: Build TDLib for Debian

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  build-debian:
    # 使用GitHub提供的Ubuntu环境（基于Debian，兼容Debian构建步骤）
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Update system and install dependencies
        run: |
          # 在GitHub Actions中无需su，已具备sudo权限
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y \
            make \
            git \
            zlib1g-dev \
            libssl-dev \
            gperf \
            php-cli \
            cmake \
            default-jdk \
            g++
      
      - name: Clone TDLib repository
        run: |
          git clone https://github.com/tdlib/td.git
          cd td
          git submodule update --init --recursive  # 初始化子模块确保完整性
      
      - name: Build and install TDLib core
        run: |
          cd td
          rm -rf build
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX:PATH=../example/java/td \
                -DTD_ENABLE_JNI=ON ..
          cmake --build . --target install --config Release
      
      - name: Build and install Java example
        run: |
          cd td/example/java
          rm -rf build
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX:PATH=../../../tdlib \
                -DTd_DIR:PATH=$(readlink -e ../td/lib/cmake/Td) ..
          cmake --build . --target install --config Release
      
      - name: List build output
        run: |
          cd td
          ls -l tdlib
          ls -l tdlib/bin
          ls -l tdlib/docs
      
      - name: Package JAR with main class
        run: |
          cd td/tdlib/bin
          jar cvfe tdlib.jar org.drinkless.tdlib.example.Example .
          mv tdlib.jar ../
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tdlib-debian-build
          path: |
            td/tdlib/
            td/tdlib/tdlib.jar
          retention-days: 30  # 构建产物保留30天
