name: Build TDLib for macOS (Apple Silicon)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-15
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read specific commit hash from file
        id: get-commit
        run: |
          # 假设commit哈希存储在仓库根目录的tdlib-commit.txt文件中
          COMMIT_HASH=$(cat tdlib-commit.txt)
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
          echo "Read commit hash: $COMMIT_HASH"
        
      - name: Install Xcode command line tools (if missing)
        run: |
          # 检查是否已安装命令行工具
          if ! xcode-select -p &> /dev/null; then
            echo "Installing Xcode command line tools..."
            xcode-select --install
            # 等待安装完成（最多等待5分钟）
            sleep 300
          else
            echo "Xcode command line tools are already installed"
          fi
      
      - name: Install Homebrew (if missing)
        run: |
          if ! command -v brew &> /dev/null; then
            echo "Installing Homebrew..."
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          else
            echo "Homebrew is already installed"
          fi
      
      - name: Install dependencies via Homebrew
        run: |
          brew install gperf cmake openssl coreutils openjdk
      
      - name: Clone TDLib repository
        run: |
          git clone https://github.com/tdlib/td.git
          cd td
          git submodule update --init --recursive
      - name: Checkout specific commit
        run: |
          cd td
          git checkout $COMMIT_HASH
          echo "Checked out commit: $COMMIT_HASH"
          
      - name: Build and install TDLib core
        run: |
          cd td
          rm -rf build
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DJAVA_HOME=/opt/homebrew/opt/openjdk/libexec/openjdk.jdk/Contents/Home/ \
                -DOPENSSL_ROOT_DIR=/opt/homebrew/opt/openssl/ \
                -DCMAKE_INSTALL_PREFIX:PATH=../example/java/td \
                -DTD_ENABLE_JNI=ON ..
          cmake --build . --target install --config Release
      
      - name: Build and install Java example
        run: |
          cd td/example/java
          rm -rf build
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DJAVA_HOME=/opt/homebrew/opt/openjdk/libexec/openjdk.jdk/Contents/Home/ \
                -DCMAKE_INSTALL_PREFIX:PATH=../../../tdlib \
                -DTd_DIR:PATH=$(greadlink -e ../td/lib/cmake/Td) ..
          cmake --build . --target install --config Release
      
      - name: List build output
        run: |
          cd td
          ls -l tdlib
          ls -l tdlib/bin
          ls -l tdlib/docs
      
      - name: Package JAR with main class
        run: |
          cd td/tdlib/bin
          jar cvfe tdlib.jar org.drinkless.tdlib.example.Example .
          mv tdlib.jar ../
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tdlib-macos-build
          path: |
            td/tdlib/
            td/tdlib/tdlib.jar
          retention-days: 30
